---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=33
      - TZ=America/New_York
      - UMASK_SET=002
      - VIRTUAL_HOST=radarr.segfault.rip
      - VIRTUAL_PORT=7878
      - LETSENCRYPT_HOST=radarr.segfault.rip
    volumes:
      - config:/config
      - /uhh:/uhh
      - /uhh/videos/movies:/movies
      - /uhh/videos/korean:/korean
      - /uhh/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - nginx-proxy
      - plex-services
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.segfault.rip/
      - homepage.description=A movie manager

networks:
  default:
  nginx-proxy:
    external: true
  plex-services:
    external: true

volumes:
  config: {}
