---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=33
      - TZ=America/New_York
      - UMASK_SET=002
      - VIRTUAL_HOST=sonarr.segfault.rip
      - VIRTUAL_PORT=8989
      - LETSENCRYPT_HOST=sonarr.segfault.rip
    volumes:
      - config:/config
      - /uhh:/uhh
      - /uhh/videos/tv:/tv
      - /uhh/videos/anime:/anime
      - /uhh/videos/korean:/korean
      - /uhh/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - nginx-proxy
      - plex-services
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=https://sonarr.segfault.rip/
      - homepage.description=A TV series manager

networks:
  default:
  nginx-proxy:
    external: true
  plex-services:
    external: true

volumes:
  config: {}
