---
version: "3"
services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    environment:
      - VIRTUAL_HOST=speedtest.segfault.rip
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=speedtest.segfault.rip
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.routers.speedtest.rule=Host(`speedtest.segfault.rip`)
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.tls.certresolver=letsencrypt

networks:
  traefik-proxy:
    external: true
