version: "3.5"
# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "31415:80/tcp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
      TZ: 'America/New_York'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD:?PIHOLE_PASSWORD must be set}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasqd:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)
    networks:
      - traefik-proxy
    labels:
      # Traefik6
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.segfault.rip`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=letsencrypt

networks:
  traefik-proxy:
    external: true

volumes:
  etc-pihole: {}
  etc-dnsmasqd: {}
