---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop
    container_name: webtop
    privileged: true #optional
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBFOLDER=/ #optional
    volumes:
      - webtop-config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    shm_size: "1gb" #optional
    restart: unless-stopped
volumes:
        webtop-config: {} 
