
on:
  push:

jobs:
  zsh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
          zsh --version
      - name: Stow Zsh Configuration
        run: |
          sudo apt-get install -y stow
          make stow zsh
      - name: Test Zsh Configuration
        shell: zsh
        run: |
          pyenv --version